import jsPDF from 'jspdf';
import { ColorHarmony } from '@/hooks/useColorHarmonies';

export const exportPaletteToPDF = (harmonies: ColorHarmony[], baseColor: string) => {
  const pdf = new jsPDF();
  
  // Set up document
  pdf.setFontSize(20);
  pdf.text('Color Harmony Palette', 20, 30);
  
  pdf.setFontSize(12);
  pdf.text(`Base Color: ${baseColor.toUpperCase()}`, 20, 45);
  
  let yPosition = 65;
  
  harmonies.forEach((harmony, harmonyIndex) => {
    // Add harmony title
    pdf.setFontSize(14);
    pdf.setFont(undefined, 'bold');
    pdf.text(harmony.name, 20, yPosition);
    
    // Add description
    pdf.setFontSize(10);
    pdf.setFont(undefined, 'normal');
    pdf.text(harmony.description, 20, yPosition + 10);
    
    // Draw color swatches
    const swatchSize = 15;
    const swatchSpacing = 20;
    
    harmony.colors.forEach((color, colorIndex) => {
      const xPosition = 20 + (colorIndex * (swatchSize + swatchSpacing));
      
      // Convert hex to RGB for PDF
      const r = parseInt(color.slice(1, 3), 16);
      const g = parseInt(color.slice(3, 5), 16);
      const b = parseInt(color.slice(5, 7), 16);
      
      // Draw color swatch
      pdf.setFillColor(r, g, b);
      pdf.rect(xPosition, yPosition + 15, swatchSize, swatchSize, 'F');
      
      // Draw border
      pdf.setDrawColor(0);
      pdf.rect(xPosition, yPosition + 15, swatchSize, swatchSize);
      
      // Add hex code below swatch
      pdf.setFontSize(8);
      pdf.text(color.toUpperCase(), xPosition, yPosition + 35);
    });
    
    yPosition += 60;
    
    // Add new page if needed
    if (yPosition > 250 && harmonyIndex < harmonies.length - 1) {
      pdf.addPage();
      yPosition = 30;
    }
  });
  
  // Add footer
  const pageCount = pdf.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.text(`Generated by Color Harmony Generator - Page ${i} of ${pageCount}`, 20, 285);
  }
  
  // Download the PDF
  const fileName = `color-palette-${baseColor.replace('#', '')}.pdf`;
  pdf.save(fileName);
};